// <auto-generated />
namespace XireManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class c6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c6));
        
        string IMigrationMetadata.Id
        {
            get { return "201912130648088_c6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
