//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XireManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XireManagerEntities : DbContext
    {
        public XireManagerEntities()
            : base("name=XireManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
       { 
        }
    
        public DbSet<Class> Classes { get; set; }
        public DbSet<Teachers> Teachers { get; set;} 
        public DbSet<Student> Student { get; set; }
        public DbSet<XireManage> XireManage { get; set;} 
        public DbSet<course> course { get; set; }
        public DbSet<SideBars> SideBars { get; set; }
        public DbSet<ActionLinks> ActionLinks { get; set; }
    }
}
